language: ruby

stages:
  - build
  - quality
  - test

install:
  - bundle install

jobs:
  include:
    - stage: build
      script: bundle exec rails db:create db:migrate
    - stage: quality
      script: bundle exec rubocop
    - stage: test
      script: bundle exec rspec
