sudo: true
language: ruby

services:
  - docker
  - postgres

stages:
  - build
  - quality
  - test

install:
  - docker-compose build
  - docker-compose up

jobs:
  include:
    - stage: build
      script:
        - docker-compose exec fortuna bundle install
        - docker-compose exec fortuna rails db:create db:migrate
    - stage: quality
      script: docker-compose exec fortuna rubocop
    - stage: test
      script: docker-compose exec fortuna rspec
