language: ruby

services:
  - postgresql

stages:
  - quality
  - test

before_install:
  - cp config/database.travis.yml config/database.yml

install:
  - bundle install
  - rails db:create db:migrate

jobs:
  include:
    - stage: quality
      script: rubocop
    - stage: test
      script: rspec --fail-fast
