sudo: true
language: ruby

services:
  - docker
  - postgres

stages:
  - quality
  - test

before_install:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker pull $DOCKER_USERNAME/fortuna:1.0.0

install:
  - docker run fortuna bundle install
  - docker run fortuna rails db:create db:migrate

jobs:
  include:
    - stage: quality
      script: docker run fortuna rubocop
    - stage: test
      script: docker run fortuna rspec
