language: ruby

services:
  - docker
  - postgres

env:
  - POSTGRES_USER=pguser
  - POSTGRES_PASSWORD=postgres

stages:
  - quality
  - test

before_install:
- docker pull eltonfonseca/fortuna:1.0.0

install:
  - docker run fortuna bundle install
  - docker run fortuna rails db:create db:migrate

jobs:
  include:
    - stage: quality
      script: docker run fortuna rubocop
    - stage: test
      script: docker run fortuna rspec
