version: '3.7'

services:
  postgres:
    image: postgres:12.3-alpine
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data,delegated

  fortuna:
    build: .
    stdin_open: true
    tty: true
    environment:
      DATABASE_URL: postgres://pguser:postgres@postgres
      TIME_ZONE: 'Brasilia'
      SECRET_KEY: '72e78abc11656ac8de91661902f6e3fcac2b2d9fc8d63d8781d63a7bd72d15b7479ce6a54a079a574eb30ac9e90eacc75fc7f99dbe81b7fdfb30030bab771920'
      CI: 'false'
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/opt/fortuna
    ports:
      - '80:3000'
    depends_on:
      - postgres