version: '3.9'

services:
  postgres:
    image: postgres:14.0-alpine
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
    ports:
      - 5432:5432
  
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 1025:1025
      - 1080:1080

  fortuna:
    build:
      context: .
      dockerfile: .devops/dockerfiles/Dockerfile
    stdin_open: true
    tty: true
    env_file: .devops/environments/.env
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/opt/fortuna
    ports:
      - 80:3000
    depends_on:
      - postgres
      - mailcatcher
